export const checkUser =(req, res, next)=>{
    try{

    } catch(err){
        console.log(err)
    }
}